### ISSUE TITLE
The text not properly erased

### ISSUE THREAD

**Issue by tnraro** [arxanas/scm-record#66] opened 2024-08-12 08:13 UTC
### Description of the bug

I'm a Jujutsu user and I'm using the built-in diff-editor.

There was a issue that the text that needed to be erased were not removed properly and still remained.

![Code_xtEfR3d3An](https://github.com/user-attachments/assets/647de23b-6db1-4667-9b55-2d0fda7cc026)

My env:

- `uname -a`: `Linux 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux`
- Console: VS Code, [Windows Terminal](https://github.com/microsoft/terminal)
- `jj --version`: `jj 0.20.0`

### Expected behavior

The text should be erased properly.

### Actual behavior

The text remains.

### Version of `rustc`

rustc 1.82.0-nightly (fbccf5053 2024-07-27)

**Comment by faldor20** [comment] 2024-08-13 00:24
I have this same issue

**Comment by mattdw** [comment] 2024-08-13 11:19
Seen on macos also -- `jj` versions 0.19.0 and 0.20.0, iTerm2 and VS Code terminal. Identical symptoms as captured above.

**Comment by arxanas** [comment] 2024-10-09 08:53
Are you using tabs? May be the same as #57. Unfortunately haven't had time to cut a release yet.

**Comment by arxanas** [comment] 2024-10-09 13:00
Closing as duplicate of https://github.com/arxanas/scm-record/issues/57; reopen if that's not the case.

**Closed** 2024-10-09 12:59 UTC
Labels: bug
